### ISSUE TITLE
encrypt_value instead of encrypted_value

### ISSUE THREAD

**Issue by djoos** [tomzo/gocd-json-config-plugin#14]
Hi there,

I ran into an issue where I had the most simple tasks (custom command of originally extracting a tar down to a straightforward echo during debug) failing. Long story short: I had one of the secure variables down with encrypt_value as key in the JSON config plugin rather than encrypted_value...

There was no obvious error showing up, however (in hindsight) I spotted that the specific secure variable was also omitted upon the _"Start to update materials"_ step (setting environment variables) on the console tab.

Not sure whether something could be done to flag something like this more clearly. At the very least it's something to be aware of as it can send a whole schoal of red herrings in someone's direction :-)

Thanks!
David

P.S. Great work on this plugin - this quickly became an essential plugin for my GoCD setup!

**Comment by arvindsv** [comment]
I think it's related to https://github.com/gocd/gocd/issues/4673 - in this case, since the `encrypted_value` was not found, I guess it was considered that it had no value and it triggered that issue. It needs more investigation to see if it's a plugin problem or a GoCD problem (more likely).
