### ISSUE TITLE
environments config not working correctly

### ISSUE THREAD

**Issue by chrobotm** [tomzo/gocd-json-config-plugin#36]
configured the environment as below, if I look at the agents tab the agent is showing the correct environment next to it but if I look on the environments page, the environment has no agents assigned to it. If I check the config xml, no agents are showing under the environment. We have multiple agents on a single server. Specifying the agent name complains about not having uuid. 

goenvironment.json

> {
  "name": "my_new_env",
  "environment_variables": [],
  "agents": [
      "243c8698-54ac-4b1e-86d7-609572390ebe"
  ],
  "pipelines": []
}

gocd 18.12
json config plugin 0.2.1

**Comment by ketan** [comment]
Are the builds being assigned correctly on the agents? Trying to understand if this is bug with just the environments page, or if its a deeper issue with agent assignment as well.

**Comment by chrobotm** [comment]
it looks like a bug with the environments page and the config xml page as the correct agent was assigned to the task. Adding the pipelines to environments in the above file works and the pipeline is showing up under the correct environment on the environments page but not the config xml page

**Comment by tomzo** [comment]
>  the pipeline is showing up under the correct environment on the environments page but not the config xml page

You should never see in XML what is already defined in config-repo (that's OK, nothing wrong with config xml page).
But clearly the bug is that UI is not showing agent in the assigned environment when agent is assigned via config-repo

**Comment by arvindsv** [comment]
Since it looks like an issue on the GoCD side, I've created: https://github.com/gocd/gocd/issues/5761 to track it. If you think this issue (here) can be closed, please do.

**Comment by tomzo** [comment]
Yep, this is not specific to json. Further discussion should happen in gocd.
