### ISSUE TITLE
Request to support 'parameters' on the pipeline

### ISSUE THREAD

**Issue by PredatorVI** [tomzo/gocd-json-config-plugin#9]
In my pipelines manually configured through the GoCD UI, I have a parameter called DEPLOY_ENV:

 ```
      <params>
        <param name="DEPLOY_ENV">acc</param>
      </params>

```
This allows me to define tasks in a more generic way by passing in the `#{DEPLOY_ENV}` as a parameter to my task definitions.  

In an effort to move to using JSON to define my configuration as code, it would be nice if I could continue this model.  

What's the chance of adding support for parameters?

**Comment by PredatorVI** [comment]
I realized after poking through the documentation a bit more that lack of parameter support for configuration repositories might be in GoCD itself.  I opened gocd/gocd#3849 as well.

**Comment by varshavaradarajan** [comment]
I think support for parameters has been around since October 18th, 2017 -  https://github.com/tomzo/gocd-json-config-plugin/commit/c0c7b40e7475d40531fb3d7294d23ae54a72decf. @tomzo - this can be closed?

**Comment by tomzo** [comment]
https://github.com/tomzo/gocd-json-config-plugin#referencing-an-existing-template-in-a-config-repo
